name: Daily TeveClub e2e UI Test

on:
  schedule:
    - cron: '0 11 * * *'  # 12:00 CET == 11:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-ui-test:
    runs-on: ubuntu-latest

    env:
      TEVE_USERNAME: ${{ secrets.TEVECLUB_USERNAME }}
      TEVE_PASSWORD: ${{ secrets.TEVECLUB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run API and UI Tests with HTML report
        run: |
          pytest tests/test_ui.py --html=report.html --self-contained-html

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: teveclub-test-report
          path: report.html
